language: node_js
sudo: false

os:
  - linux

dist:
  - xenial

node_js:
  - "10.15.1"

services:
  - xvfb

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      service xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run symlink

script:
  - npm run compile
  - npm run test